apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.names }} #{{ include "helm-chart.fullname" . }}
  labels:
    app: {{ .Values.labels.app }} #{{- include "helm-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      nodePort: {{ .Values.service.nodePort }}
    
    - name: metrics
      port: {{ .Values.servicemonitor.port }}
      targetPort: {{ .Values.servicemonitor.targetPort }}
      protocol: {{ .Values.servicemonitor.protocol }}

  selector:
    app: {{ .Values.labels.app }} #{{- include "helm-chart.selectorLabels" . | nindent 4 }}
    #app: {{ include "helm-chart.fullname" . }}
    