apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/instance: k8s
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: "39.9.0"
  name: applications
  namespace: monitoring
spec:
  image: "quay.io/prometheus/prometheus:v2.37.0"
  replicas: 1
  version: v2.37.0
  nodeSelector:
    kubernetes.io/os: linux
  serviceAccountName: prometheus-k8s
  serviceMonitorNamespaceSelector: {} #match all namespaces
  serviceMonitorNamespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: test
  serviceMonitorSelector: {} #match all servicemonitors
