apiVersion: external-secret.io/v1
kind:  ClusterSecretStore
metadata:
  name: aws
spec: 
  provider:
    awssm:
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: aws
            key: credentials
            namespace:
      projectID:

