apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}  
type: Opaque
data:
  DB_USER:      {{ .Values.username | b64enc }}   #cGV4b24tdHJhaW5pbmc= 
  DB_PASSWORD:  {{ .Values.password | b64enc }}     #cGV4b24tdHJhaW5pbmcyMDIyZ2F0ZWtlZXBlcg== 
  DB_IP:        {{ .Values.ip | b64enc }}     #MzQuMTU5LjMuMTI3
  DB_NAME:      {{ .Values.name | b64enc }}     #Ym9va3M= 